services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /var/data/caddy/site-enabled:/var/data/caddy/site-enabled
      - /var/data/caddy/data:/data
      - /var/data/caddy/config:/config
