services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/data/jellyfin/config:/config
      - /var/data/jellyfin/cache:/cache
      - type: bind
        source: /storage
        target: /media
    ports:
      - "8096:8096"
      - "8920:8920"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
